/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Fluent 2 neutrals + brand green
        "inverse-on-surface": "#f5f5f5",
        "outline-variant": "#d1d1d1",
        "on-surface": "#242424",
        "secondary-fixed": "#bef500",
        "on-background": "#242424",
        "surface-container": "#ebebeb",
        "tertiary": "#424242",
        "on-tertiary-container": "#d1d1d1",
        "surface-tint": "#2a6b2c",
        "background": "#f3f3f3",
        "on-secondary-container": "#526b00",
        "secondary": "#4e6700",
        "error-container": "#fde7e9",
        "primary-container": "#1b5e20",
        "on-tertiary-fixed": "#1c1c1c",
        "on-secondary-fixed": "#151f00",
        "on-primary-fixed": "#002203",
        "on-tertiary-fixed-variant": "#474747",
        "tertiary-fixed": "#e5e5e5",
        "on-primary-container": "#90d689",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e1e1e1",
        "primary-fixed": "#acf4a4",
        "secondary-container": "#bcf200",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c8c8c8",
        "on-secondary-fixed-variant": "#3a4d00",
        "surface-container-high": "#e0e0e0",
        "primary": "#00450d",
        "on-error-container": "#751010",
        "on-primary-fixed-variant": "#0c5216",
        "inverse-surface": "#323232",
        "inverse-primary": "#91d78a",
        "surface": "#fafafa",
        "primary-fixed-dim": "#91d78a",
        "secondary-fixed-dim": "#a6d700",
        "on-surface-variant": "#616161",
        "tertiary-container": "#525252",
        "surface-bright": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline": "#8a8a8a",
        "surface-container-highest": "#d1d1d1",
        "surface-container-low": "#f5f5f5",
        "error": "#c50f1f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 0 2px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.14)",
        DEFAULT: "0 0 2px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.14)",
        md: "0 0 2px rgba(0,0,0,0.12), 0 4px 8px rgba(0,0,0,0.14)",
        lg: "0 0 2px rgba(0,0,0,0.12), 0 8px 16px rgba(0,0,0,0.14)",
        fluent: "0 0 2px rgba(0,0,0,0.12), 0 4px 8px rgba(0,0,0,0.14)",
        "2xl": "0 0 8px rgba(0,0,0,0.12), 0 32px 64px rgba(0,0,0,0.28)",
      },
      transitionTimingFunction: {
        "fluent-decel": "cubic-bezier(0.1, 0.9, 0.2, 1)",
        "fluent-accel": "cubic-bezier(0.9, 0.1, 1, 0.2)",
        "fluent-std": "cubic-bezier(0.33, 0, 0.67, 1)",
      },
      keyframes: {
        "fluent-in": { from: { opacity: "0", transform: "translateY(12px)" }, to: { opacity: "1", transform: "none" } },
        "fluent-fade": { from: { opacity: "0" }, to: { opacity: "1" } },
        "fluent-scale": { from: { opacity: "0", transform: "scale(0.96)" }, to: { opacity: "1", transform: "none" } },
        "bar-grow": { from: { transform: "scaleX(0)" }, to: { transform: "scaleX(1)" } },
      },
      animation: {
        "fluent-in": "fluent-in 350ms cubic-bezier(0.1,0.9,0.2,1) backwards",
        "fluent-fade": "fluent-fade 250ms cubic-bezier(0.33,0,0.67,1) both",
        "fluent-scale": "fluent-scale 200ms cubic-bezier(0.1,0.9,0.2,1) both",
        "bar-grow": "bar-grow 700ms cubic-bezier(0.1,0.9,0.2,1) 150ms backwards",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "gutter": "0.75rem",
        "gutter-mobile": "0.5rem",
        "margin": "1rem",
        "margin-mobile": "0.75rem",
      },
      fontFamily: {
        "headline-lg": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        "title-sm": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        "body-sm": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        "label-data-sm": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        "headline-xl": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        "headline-md": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        "label-caps": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        "headline-xl-mobile": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        "body-md": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
        "label-data-lg": ["Segoe UI Variable Text", "Segoe UI", "system-ui", "-apple-system", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-sm": ["14px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "label-data-sm": ["18px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["36px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "20px", fontWeight: "400" }],
        "label-data-lg": ["32px", { lineHeight: "34px", letterSpacing: "-0.03em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
